services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      - DATABASE_URL=sqlite:///./store_intelligence.db
      - ENV=dev
      - PORT=8000
    restart: always
